FROM simulogic-env

# # Build server
WORKDIR /app
COPY . .

# RUN yarn build server

# Deploy server
CMD ["node", "dist/apps/server/main"]
EXPOSE 80
# CMD echo "$CLASSPATH" # antlr jar present and classpath ok but still doesnt find org..antlr when LogicToCpp executed