FROM simulogic-env as react-build

WORKDIR /app

COPY . .

RUN yarn build interface

# Stage 2 - the production environment
FROM nginx:alpine
WORKDIR /app
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/dist/apps/interface /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]