FROM debian

WORKDIR /app
COPY package.json .

RUN apt-get update
RUN apt-get install -y curl gnupg2
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn
RUN apt-get install -y nodejs

RUN apt-get install -y openjdk-11-jdk
RUN curl -O https://www.antlr.org/download/antlr-4.7.2-complete.jar
ENV CLASSPATH=".:antlr-4.7.2-complete.jar:$CLASSPATH"

RUN apt-get install -y make g++

RUN yarn
