version: "3"

services:
  mysql:
    container_name: db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  
  # web:
  #   container_name: interface
  #   image: nginx:alpine
  #   volumes:
  #     - ./dist/apps/interface:/usr/share/nginx/html
  #     - ./dist/apps/interface:/var/www/html
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"

  # nest:
  #   container_name: server
  # ?