version: "3"

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    container_name: db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./data:/data/db

    labels:
        traefik.enable: "true"
        traefik.http.routers.db.rule: "Host(`db.localhost`)"
        traefik.http.services.db.loadbalancer.server.port: "3306"

  simulogic-interface:
    build:
      context: .
      dockerfile: Dockerfile.interface
    # image: simulogic-interface
    labels:
        traefik.enable: "true"
        traefik.http.routers.interface.rule: "Host(`interface.localhost`)"
        traefik.http.services.interface.loadbalancer.server.port: "80"
      
  simulogic-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    # image: simulogic-server
    depends_on: 
      - db
    labels:
        traefik.enable: "true"
        traefik.http.routers.server.rule: "Host(`server.localhost`)"
        traefik.http.services.server.loadbalancer.server.port: "80"
  

