FROM simulogic-env as env

WORKDIR /app
COPY . .

# Build interface
RUN yarn build interface

# Deploy interface
FROM nginx:alpine
WORKDIR /app
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=env /app/dist/apps/interface /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]