import { Column, Entity, JoinColumn, OneToOne, PrimaryGeneratedColumn } from 'typeorm';
import { CircuitFile } from '../circuitFiles/circuitFile.entity';
import { SimulationFile } from '../simulationFiles/simulationFile.entity';

/**
 * Database table entity to save a generated result file.
 */
@Entity()
export class ResultFile {

  /**
   * UUID of ResultFile entity.
   */
  @PrimaryGeneratedColumn("uuid")
  uuid: string;

  /**
   * Path of result file.
   */
  @Column()
  path: string;

  /**
   * CircuitFile entity linked to ResultFile entity
   * (result file generated by this circuit file simulator).
   */
  @OneToOne(type => CircuitFile, { cascade: true, onDelete: "CASCADE", primary: true })
  @JoinColumn()
  circuit_file: CircuitFile;

  /**
   * SimulationFile entity linked to ResultFile entity
   * (result file generated with this simulation file).
   */
  @OneToOne(type => SimulationFile, { cascade: true, onDelete: "CASCADE", primary: true })
  @JoinColumn()
  simulation_file: SimulationFile;
}
